:hidecomments:

[source,rust]
----
tag::app_name[]
    const APP_NAME: &'static str = "Part 2: Push constants";
end::app_name[]
----

Blah blah, explain what push constants are.

Let's define a struct to hold our push constants:

[source,rust]
----
tag::push_constants_struct[]
#[repr(C)]
#[derive(Debug, Clone, Copy)]
struct PushConstants {
    color: [f32; 4],
    pos: [f32; 2],
    scale: [f32; 2],
}
end::push_constants_struct[]
----

And before our main loop, let's also give ourselves a time parameter, so we can animate things.

[source,rust]
----
tag::start_time[]
    let start_time = std::time::Instant::now();
end::start_time[]

    event_loop.run(move |event, _, control_flow| {
        // ...
----

We have to make two small changes to our pipeline to enable push constants. First is in the layout.

For each draw call, we're going to supply one of our `PushConstants` structs. However, the GPU doesn't know anything about structs - all it knows is that we're going to give it some bytes. What it wants to know is _which_ of those bytes it should use for a specific shader stage. In our case, we only care about the vertex shader, and the number of bytes is however big the struct is:

[source,rust]
----
tag::pipeline_layout[]
    let pipeline_layout = unsafe {
        use gfx_hal::pso::ShaderStageFlags;

        let push_constant_bytes = std::mem::size_of::<PushConstants>() as u32;
        device
            .create_pipeline_layout(&[], &[(ShaderStageFlags::VERTEX, 0..push_constant_bytes)])
            .expect("TODO")
    };
end::pipeline_layout[]
----

The other change is in our shaders. We need to allow them to make use of the new information we're supplying:

_TODO_: Put the new shaders here
[source,glsl]
----
// Vertex shader
tag::vertex_shader[]
#version 450
#extension GL_ARB_separate_shader_objects : enable

vec2 positions[3] = vec2[](
    vec2(0.0, -0.5),
    vec2(-0.5, 0.5),
    vec2(0.5, 0.5)
);

layout(push_constant) uniform PushConstants {
    vec4 color;
    vec2 pos;
    vec2 scale;
} push_constants;

layout(location = 0) out vec4 vertex_color;

void main() {
    vec2 pos = positions[gl_VertexIndex] * push_constants.scale;
    vertex_color = push_constants.color;
    gl_Position = vec4((pos + push_constants.pos), 0.0, 1.0);
}
end::vertex_shader[]
----

[source,glsl]
----
// Fragment shader
tag::fragment_shader[]
#version 450
#extension GL_ARB_separate_shader_objects : enable

layout(location = 0) in vec4 vertex_color;

layout(location = 0) out vec4 fragment_color;

void main() {
    fragment_color = vertex_color;
}
end::fragment_shader[]
----

And of course, use the new files:

[source,rust]
----
        // ...
tag::shaders[]
        let vertex_shader_module =
            compile_shader(include_str!("shaders/part-2.vert"), ShaderType::Vertex);

        let fragment_shader_module =
            compile_shader(include_str!("shaders/part-2.frag"), ShaderType::Fragment);
end::shaders[]
        // ...
----

Now finally, we can make use of our push constants to render some things. So let's replace our old draw call:

[source,rust]
----
include::part-1-triangle.adoc[tag=draw_call]
----

With something more interesting. First we'll define the data we want to draw:

[source,rust]
----
tag::push_constant_data[]
                    let anim = start_time.elapsed().as_secs_f32().sin() * 0.5 + 0.5;
                    let small = [0.33, 0.33];

                    let things_to_draw = &[
                        PushConstants {
                            color: [1.0, 0.0, 0.0, 1.0],
                            pos: [-0.5, -0.5],
                            scale: small,
                        },
                        PushConstants {
                            color: [0.0, 1.0, 0.0, 1.0],
                            pos: [0.0, -0.5],
                            scale: small,
                        },
                        PushConstants {
                            color: [0.0, 0.0, 1.0, 1.0],
                            pos: [0.5, -0.5],
                            scale: small,
                        },
                        PushConstants {
                            color: [0.0, anim, 1.0, 1.0],
                            pos: [-0.5, 0.5],
                            scale: small,
                        },
                        PushConstants {
                            color: [1.0, 1.0, 1.0, 1.0],
                            pos: [0.0, 0.5 - anim * 0.5],
                            scale: small,
                        },
                        PushConstants {
                            color: [1.0, 1.0, 1.0, 1.0],
                            pos: [0.5, 0.5],
                            scale: [0.33 + anim * 0.33, 0.33 + anim * 0.33],
                        },
                    ];
end::push_constant_data[]
----

Then we'll draw a triangle for each one:

[source,rust]
----
tag::draw_call[]
                    for thing in things_to_draw {
                        use gfx_hal::pso::ShaderStageFlags;

                        let size_in_bytes = std::mem::size_of::<PushConstants>();
                        let size_in_u32s = size_in_bytes / std::mem::size_of::<u32>();
                        let start_ptr = thing as *const PushConstants as *const u32;
                        let bytes = std::slice::from_raw_parts(start_ptr, size_in_u32s);
                        command_buffer.push_graphics_constants(
                            &res.pipeline_layout,
                            ShaderStageFlags::VERTEX,
                            0,
                            bytes,
                        );

                        command_buffer.draw(0..3, 0..1);
                    }
end::draw_call[]
----
